// Initial Test Framework Generated by ChatGPT...
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include "andy_arena.h"
#include "andy_runtime.h"
#include "andy_types.h"
#include "andy_error.h"
#include "andy_io.h"

/* ---------- Arena Tests ---------- */

static void test_arena_basic(void) {
  printf("Running test_arena_basic...\n");

  arena_t* a = arena_create(64);
  assert(a);

  int* x = arena_alloc(a, sizeof *x, alignof(int));
  double* y = arena_alloc(a, sizeof *y, alignof(double));
  char* s = arena_alloc(a, 10, alignof(char));

  assert(x && y && s);
  *x = 42;
  *y = 3.14159;
  strcpy(s, "test");

  assert(*x == 42);
  assert(*y > 3.14 && *y < 3.15);
  assert(strcmp(s, "test") == 0);

  arena_destroy(a);
  printf("[PASS] test_arena_basic\n\n");
}

static void test_arena_growth(void) {
  printf("Running test_arena_growth...\n");

  arena_t* a = arena_create(32);
  assert(a);

  for (int i = 0; i < 100; i++) {
    int* p = arena_alloc(a, sizeof *p, alignof(int));
    assert(p);
    *p = i;
  }

  arena_destroy(a);
  printf("[PASS] test_arena_growth\n\n");
}

/* ---------- Runtime Tests ---------- */

static void test_runtime_init_shutdown(void) {
  printf("Running test_runtime_init_shutdown...\n");

  andy_runtime_init();
  arena_t* a = andy_get_global_arena();
  assert(a);

  int* x = arena_alloc(a, sizeof *x, alignof(int));
  assert(x);
  *x = 123;
  assert(*x == 123);

  andy_runtime_shutdown();
  printf("[PASS] test_runtime_init_shutdown\n\n");
}

/* ---------- Types Tests ---------- */

static void test_andy_string(void) {
  printf("Running test_andy_string...\n");

  arena_t* a = arena_create(128);
  assert(a);

  andy_string* s = arena_alloc(a, sizeof *s, alignof(andy_string));
  s->length = 5;
  s->data = arena_alloc(a, 6, alignof(char));
  memcpy(s->data, "hello", 6);

  assert(s->length == 5);
  assert(strcmp(s->data, "hello") == 0);

  arena_destroy(a);
  printf("[PASS] test_andy_string\n\n");
}

/* ---------- Error Handling Tests ---------- */

static void test_andy_warn(void) {
  printf("Running test_andy_warn...\n");
  andy_warn("This is a test warning (expected)");
  printf("[PASS] test_andy_warn\n\n");
}

static void test_andy_assert(void) {
  printf("Running test_andy_assert...\n");
  andy_assert(1, "This should not fail");
  printf("[PASS] test_andy_assert\n\n");
}

/* ---------- I/O Tests ---------- */

static void test_andy_read_string(void) {
  printf("Running test_andy_read_string...\n");
  printf("Please enter the string: hello\n");

  arena_t* a = arena_create(128);
  assert(a);

  andy_string* s = andy_read_string(a);
  assert(s);
  assert(strcmp(s->data, "hello") == 0);
  assert(s->length == 5);

  arena_destroy(a);
  printf("[PASS] test_andy_read_string\n\n");
}

/* ---------- Main ---------- */

int main(void) {
  printf("Starting Andy runtime tests...\n\n");

  test_arena_basic();
  test_arena_growth();
  test_runtime_init_shutdown();
  test_andy_string();
  test_andy_warn();
  test_andy_assert();
  test_andy_read_string();

  printf("All tests passed successfully.\n");
  return 0;
}

